// @ts-check
/** @type {import("@next-core/test-next").TestNextConfig} */
export default {
  transformModulePatterns: [
    "(?:hast|unist|mdast|estree)-util-(?:[^/]+)/",
    "unified/",
    "bail/",
    "devlop/",
    "is-plain-obj/",
    "trough/",
    "vfile/",
    "vfile-message/",
    "decode-named-character-reference/",
    "ccount/",
    "escape-string-regexp/",
    "markdown-table/",
    "longest-streak/",
    "zwitch/",
    "trim-lines/",
    "property-information/",
    "is-absolute-url/",
    "space-separated-tokens/",
    "comma-separated-tokens/",
    "micromark/",
    "micromark-(?:[^/]+)/",
    "remark-(?:[^/]+)/",
    "rehype-(?:[^/]+)/",
    "@shikijs/",
    "shiki/",
    "html-void-elements/",
    "hastscript/",
    "web-namespaces/",
    "stringify-entities/",
    "character-entities-(?:[^/]+)/",
  ],
};
