install_path: /usr/local/easyops/bricks/basic-NB
user: "easyops:easyops"
dependencies:
  - name: brick_next
    version: ^2.86.3 || ^3.0.0
    local_deploy: true
  - name: "@next-bricks/shoelace"
    version: ^0.4.1
    local_deploy: true
  - name: "@next-bricks/icons"
    version: ^0.2.1
    local_deploy: true
